UI: Handle clearing of Number filter correctly
When clearing the number filter in a filterable table, an error is
thrown in the JS console of the form:
```
oojs.js:867 Uncaught TypeError: this.operatorWidget.selectItemByData is not a function
    at OOJSPlus.ui.data.filter.Number.clearValues (Number.js:82:22)
    at OOJSPlus.ui.data.filter.FilterItem.click (FilterItem.js:46:16)
    at OO.EventEmitter.emit (oojs.js:858:12)
    at OO.ui.mixin.ButtonElement.onClick (oojs-ui-core.js:2377:13)
    at HTMLAnchorElement.dispatch (jquery.js:5145:27)
    at elemData.handle (jquery.js:4949:28)
```

This is because the clearing of the filter was done incorrectly
by instead selecting items of the underlying data attributes instead
of clearing the field and closing the component.

Test plan
=========

1. Try to filter the able column based on a particular value
2. Once done, close the filter and ensure errors are thrown in the
   JS console.

Before this patch, the filter is actually not closed.

[5.2.x]

ERM50361

Change-Id: I6f5c734a450b17d25023641a19b5be613629e86b